package googlesql_test

import (
	"fmt"
	"strings"
	"testing"

	"github.com/goccy/go-googlesql"
)

// TestWalk traverses the AST of a SELECT statement manually through the
// typed accessors, capturing each visited node's concrete type. A
// generic Walk() over ASTNode is not yet generated by the plugin (it
// would require a kind + child_nodes RPC on the abstract class plus a
// dispatch table); until that lands, this test stands in for the
// go-zetasql TestWalk by asserting every pivotal accessor reaches the
// expected node type.
func TestWalk(t *testing.T) {
	t.Cleanup(gc)

	opts, err := googlesql.NewParserOptions()
	if err != nil {
		t.Fatalf("NewParserOptions: %v", err)
	}
	out, err := googlesql.ParseStatement("SELECT id, name FROM Samples WHERE id = 1", opts)
	if err != nil {
		t.Fatalf("ParseStatement: %v", err)
	}
	stmt, err := out.Statement()
	if err != nil {
		t.Fatalf("Statement: %v", err)
	}

	var visited []string
	visit := func(prefix string, node interface{}) {
		visited = append(visited, fmt.Sprintf("%s=%T", prefix, node))
	}
	visit("statement", stmt)

	queryStmt, ok := stmt.(*googlesql.ASTQueryStatement)
	if !ok {
		t.Fatalf("expected *googlesql.ASTQueryStatement, got %T", stmt)
	}
	query, err := queryStmt.Query()
	if err != nil {
		t.Fatalf("Query: %v", err)
	}
	visit("query", query)

	queryExpr, err := query.QueryExpr()
	if err != nil {
		t.Fatalf("QueryExpr: %v", err)
	}
	visit("query_expr", queryExpr)

	sel, ok := queryExpr.(*googlesql.ASTSelect)
	if !ok {
		t.Fatalf("expected *googlesql.ASTSelect, got %T", queryExpr)
	}

	selectList, err := sel.SelectList()
	if err != nil {
		t.Fatalf("SelectList: %v", err)
	}
	// The query has two columns by construction; iterate only that
	// many. There is no size accessor on ASTSelectList that the public
	// API exposes — Columns(n) past the end would read garbage and we'd
	// get a wasm out-of-bounds error.
	for i := int32(0); i < 2; i++ {
		col, colErr := selectList.Columns(i)
		if colErr != nil {
			t.Fatalf("Columns(%d): %v", i, colErr)
		}
		expr, exprErr := col.Expression()
		if exprErr != nil {
			t.Fatalf("Columns(%d).Expression: %v", i, exprErr)
		}
		visit(fmt.Sprintf("select_col[%d].expr", i), expr)
	}

	fromClause, err := sel.FromClause()
	if err != nil {
		t.Fatalf("FromClause: %v", err)
	}
	tableExpr, err := fromClause.TableExpression()
	if err != nil {
		t.Fatalf("TableExpression: %v", err)
	}
	visit("from.table_expr", tableExpr)

	whereClause, err := sel.WhereClause()
	if err != nil {
		t.Fatalf("WhereClause: %v", err)
	}
	whereExpr, err := whereClause.Expression()
	if err != nil {
		t.Fatalf("WhereClause.Expression: %v", err)
	}
	visit("where.expr", whereExpr)

	if bin, ok := whereExpr.(*googlesql.ASTBinaryExpression); ok {
		lhs, _ := bin.Lhs()
		rhs, _ := bin.Rhs()
		visit("where.lhs", lhs)
		visit("where.rhs", rhs)
	}

	report := strings.Join(visited, "\n")
	t.Logf("AST walk:\n%s", report)
	wants := []string{
		"statement=*googlesql.ASTQueryStatement",
		"query_expr=*googlesql.ASTSelect",
		"from.table_expr=*googlesql.ASTTablePathExpression",
		"where.expr=*googlesql.ASTBinaryExpression",
	}
	for _, w := range wants {
		if !strings.Contains(report, w) {
			t.Errorf("walk report missing %q", w)
		}
	}
}
